# Generated by Django 5.2.4 on 2026-04-29 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
